"""update_match_model

Revision ID: 5fec4f4a9725
Revises: a7551e8d11c5
Create Date: 2025-04-28 21:22:08.339552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fec4f4a9725'
down_revision = 'a7551e8d11c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('matches', 'liked_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'matches', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.alter_column('matches', 'liked_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('matches', 'project_id')
    # ### end Alembic commands ### 