"""update_like_model_nullable_fields

Revision ID: 72360f22887e
Revises: 5fec4f4a9725
Create Date: 2025-04-28 21:42:06.056608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72360f22887e'
down_revision = '5fec4f4a9725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'liked_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('likes', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'liked_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ### 