"""remove_project_matches

Revision ID: a7551e8d11c5
Revises: ae0f5224df2d
Create Date: 2025-04-28 20:28:47.078413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7551e8d11c5'
down_revision = 'ae0f5224df2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 