input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [container][name] =~ /backend/ {
    json {
      source => "message"
      target => "app"
      skip_on_invalid_json => true
    }
  }

  mutate {
    remove_field => ["ecs", "input", "agent"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "finder-logs-%{+YYYY.MM.dd}"
  }
}
